[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "marketsimulator"
version = "0.1.0"
dependencies = [
    "pydantic>=2.13",
    "pydantic-settings>=2.14",
    "pandas",
    "pyarrow",
    "confluent-kafka",
    "python-dotenv",
    "dask[dataframe]>=2026.7.1"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]
